//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSC2015_Redo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Runner_View
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string RegistrationStatus { get; set; }
        public string EventTypeName { get; set; }
        public byte MarathonId { get; set; }
        public int RunnerId { get; set; }
    }
}
