//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSC2015_Redo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor_View
    {
        public string Expr1 { get; set; }
        public int RegistrationEventId { get; set; }
        public byte MarathonId { get; set; }
    }
}
